version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/eliana_cinema
    command: >
      sh -c "python manage.py migrate &&
             gunicorn eliana.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=eliana_cinema
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: